name: Auto Release

on:
  pull_request:
    types: [closed]  # Runs only when a PR is merged
    branches:
      - master  # Only trigger on merges to master
  workflow_dispatch: {}  # Allows manual trigger

jobs:
  release:
    if: github.event.pull_request.merged == true  # Ensures only runs on merge
    needs: [build-and-test, analyze, audit, lint]  # Ensures all workflows must pass first
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build

      - name: Extract changelog entry
        id: changelog
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          snippet=$(awk "/^## \\[?$VERSION\\]?\\(?/,/^## /{print}" CHANGELOG.md | sed '$d')
          echo "changelog<<EOF" >> GITHUB_ENV
          echo "$snippet"       >> GITHUB_ENV
          echo "EOF"           >> GITHUB_ENV

      - name: Zip extension folder
        run: |
          mkdir extension
          mkdir extension/dist
          cp manifest.json extension/
          cp dist/content.bundle.js extension/dist/
          zip -r "duolingo-hard-mode.zip" extension

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          draft: false
          prerelease: false
          body: ${{ env.changelog }}

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: duolingo-hard-mode.zip
          asset_name: duolingo-hard-mode.zip
          asset_content_type: application/zip
